[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200

build_flags = 
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=0

lib_deps = 
    lovyan03/LovyanGFX @ ^1.1.16
    h2zero/NimBLE-Arduino @ ^1.4.2
    bitbank2/AnimatedGIF @ ^2.1.1
